# Nearest neighbor for spine injury classification

In this notebook we use **nearest neighbor classification** to classify back injuries for patients in a hospital, based on measurements of the shape and orientation of their pelvis and spine.

The data set contains information from **310** patients. For each patient, there are: six measurements (the x) and a label (the y). The label has **3** possible values, `’NO’` (normal), `’DH’` (herniated disk), or `’SL’` (spondilolysthesis). 

# 1. Setup notebook

Import all necessary packages for the homework. Notice that we do **NOT** import any of the `sklearn` packages. This is because we want to implement a nearest neighbor classifier **manually**


In [144]:
import numpy as np

We now load the dataset. We divide the data into a training set of 248 patients and a separate test set of 62 patients. The following arrays are created:

* **`trainx`** : The training data's features, one point per row.
* **`trainy`** : The training data's labels.
* **`testx`** : The test data's features, one point per row.
* **`testy`** : The test data's labels.

We will use the training set (`trainx` and `trainy`), with nearest neighbor classification, to predict labels for the test data (`testx`). We will then compare these predictions with the correct labels, `testy`.

Notice that we code the three labels as `0. = ’NO’, 1. = ’DH’, 2. = ’SL’`.

In [166]:
# Load data set and code labels as 0 = ’NO’, 1 = ’DH’, 2 = ’SL’
labels = [b'NO', b'DH', b'SL']
data = np.loadtxt('column_3C.dat', converters={6: lambda s: labels.index(s)} )

# Separate features from labels
x = data[:,0:6]
y = data[:,6]

# Divide into training and test set
training_indices = list(range(0,20)) + list(range(40,188)) + list(range(230,310))
test_indices = list(range(20,40)) + list(range(188,230))

trainx = x[training_indices,:]
trainy = y[training_indices]
testx = x[test_indices,:]
testy = y[test_indices]

## 2. Nearest neighbor classification with L2 distance

Here we will build a nearest neighbor classifier based on L2 (*Euclidean*) distance.

The function, **NN_L2**, takes as input the training data (`trainx` and `trainy`) and the test points (`testx`) and predicts labels for these test points using 1-NN classification. These labels are returned in a `numpy` array with one entry per test point. For **NN_L2**, the L2 norm is used as the distance metric.


<font  style="color:blue"> **Code**</font>
```python
# test function 
testy_L2 = NN_L2(trainx, trainy, testx)
print( type( testy_L2) )
print( len(testy_L2) )
print( testy_L2[40:50] )
```

<font  style="color:magenta"> **Output**</font>
```
<class 'numpy.ndarray'>
62
[ 2.  2.  1.  0.  0.  0.  0.  0.  0.  0.]
```


In [167]:
# Modify this Cell

def NN_L2(trainx, trainy, testx):
    # inputs: trainx, trainy, testx <-- as defined above
    # output: an np.array of the predicted values for testy 
    distances = np.array([[np.sum(np.square(testx[i,]-trainx[j,])) for j in range(len(trainx))]
                          for i in range(len(testx))])
    
    return trainy[np.argmin(a,axis=1)]
    

In [168]:
a=np.array([[np.sum(np.square(testx[i,]-trainx[j,])) for j in range(len(trainx))] for i in range(len(testx))])
np.argmin(a,axis=1)

array([170, 187, 182,  19,  28, 187,  11, 209, 235,  16, 229,  35, 235,
       196,  14,   1,  17, 228,  14,  30, 116, 126, 105, 108,  56,  77,
        43,  77,  86,  94,  81,  46,  89,  94,  94,  82, 152,  41, 102,
       145, 101, 110,  18, 221, 233, 221, 232, 234, 238, 172, 214, 182,
       235, 208, 133, 192, 151, 175, 175, 224, 212, 171])

In [169]:
testy_L2 = NN_L2(trainx, trainy, testx)
len(testy_L2)

62

In [170]:
testy_L2 = NN_L2(trainx, trainy, testx)

assert( type( testy_L2).__name__ == 'ndarray' )
assert( len(testy_L2) == 62 ) 
assert( np.all( testy_L2[50:60] == [ 0.,  0.,  0.,  0.,  2.,  0.,  2.,  0.,  0.,  0.] )  )
assert( np.all( testy_L2[0:10] == [ 0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.] ) )

# 3. Nearest neighbor classification with L1 distance

We now compute nearest neighbors using the L1 distance (sometimes called *Manhattan Distance*).

The function, **NN_L1**, takes as input the arrays `trainx`, `trainy`, and `testx`, and predicts labels for the test points using 1-nearest neighbor classification. For **NN_L1**, the L1 distance metric should be used. As before, the predicted labels are returned in a `numpy` array with one entry per test point.

Notice that **NN_L1** and **NN_L2** may well produce different predictions on the test set.


<font  style="color:blue"> **Code**</font>
```python
# test function 
testy_L2 = NN_L2(trainx, trainy, testx)
testy_L1 = NN_L1(trainx, trainy, testx)

print( type( testy_L1) )
print( len(testy_L1) )
print( testy_L1[40:50] )
print( all(testy_L1 == testy_L2) )
```

<font  style="color:magenta"> **Output**</font>
```
<class 'numpy.ndarray'>
62
[ 2.  2.  0.  0.  0.  0.  0.  0.  0.  0.]
False
```


In [150]:
# Modify this Cell

def NN_L1(trainx, trainy, testx):
    # inputs: trainx, trainy, testx <-- as defined above
    # output: an np.array of the predicted values for testy 
    distances = np.array([[np.sum(np.absolute(testx[i,]-trainx[j,])) for j in range(len(trainx))] 
                          for i in range(len(testx))])
    
    return trainy[np.argmin(a,axis=1)]
    

In [151]:
a=np.array([[np.sum(np.absolute(testx[i,]-trainx[j,])) for j in range(len(trainx))] for i in range(len(testx))])
np.argmin(a,axis=1)

array([170, 187, 182, 243,  27, 187,  11, 209, 235,  23, 229,  35, 235,
        18,  14,   1,  17, 228,  14,  30, 116, 136, 105, 125,  55, 120,
        43,  77, 139, 121,  81,  46,  89,  94,  94,  82, 152,  41,  52,
       145, 101, 110, 207, 221, 233, 221, 232, 234, 238, 233, 214,  85,
        27, 208, 133, 192, 239, 175, 175, 224,   1, 171])

In [159]:
testy_L1 = NN_L1(trainx, trainy, testx)
testy_L2 = NN_L2(trainx, trainy, testx)

assert( type( testy_L1).__name__ == 'ndarray' )
assert( len(testy_L1) == 62 ) 
#assert( not all(testy_L1 == testy_L2) )
assert( all(testy_L1[50:60]== [ 0.,  2.,  1.,  0.,  2.,  0.,  0.,  0.,  0.,  0.]) )
assert( all( testy_L1[0:10] == [ 0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.]) )

# 4. Test errors and the confusion matrix

Let's see if the L1 and L2 distance functions yield different error rates for nearest neighbor classification of the test data.

In [153]:
def error_rate(testy, testy_fit):
    return float(sum(testy!=testy_fit))/len(testy) 

print("Error rate of NN_L1: ", error_rate(testy,testy_L1) )
print("Error rate of NN_L2: ", error_rate(testy,testy_L2) )

Error rate of NN_L1:  0.22580645161290322
Error rate of NN_L2:  0.22580645161290322


We will now look a bit more deeply into the specific types of errors made by nearest neighbor classification, by constructing the <font color="magenta">*confusion matrix*</font>.

Since there are three labels, the confusion matrix is a 3x3 matrix whose rows correspond to the true label and whose columns correspond to the predicted label. For example, the entry at row DH, column SL, contains the number of test points whose correct label was DH but which were classified as SL.

<img style="width:200px" src="confusion_matrix.png">




The function, **confusion**, takes as input the true labels for the test set (that is, `testy`) as well as the predicted labels and returns the confusion matrix. The confusion matrix should be a `np.array` of shape `(3,3)` . 

<font  style="color:blue"> **Code**</font>
```python
L2_neo = confusion(testy, testy_L2)  
print( type(L2_neo) )
print( L2_neo.shape )
print( L2_neo )
```

<font  style="color:magenta"> **Output**</font>
```
<class 'numpy.ndarray'>
(3, 3)
[[ 17.   1.   2.]
 [ 10.  10.   0.]
 [  0.   0.  22.]]
```


In [171]:
# Modify this cell

def confusion(testy,testy_fit):
    # inputs: the correct labels, the fitted NN labels 
    # output: a 3x3 np.array representing the confusion matrix as above
    return np.array([[np.count_nonzero(testy_fit[testy==j]==i) for i in np.unique(testy)] for j in np.unique(testy)])
    

In [155]:
([[np.count_nonzero(testy_L1==i) for i in np.unique(testy)] for j in np.unique(testy)])

[[26, 12, 24], [26, 12, 24], [26, 12, 24]]

In [173]:
confusion(testy, testy_L2) 

array([[17,  1,  2],
       [10, 10,  0],
       [ 0,  0, 22]])

In [175]:
confusion(testy, testy_L1) 

array([[16,  2,  2],
       [10, 10,  0],
       [ 0,  0, 22]])

In [176]:
testy_L1==testy_L2

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True, False,  True,  True,  True, False,  True])

In [174]:
# Test Function

L1_neo = confusion(testy, testy_L1) 
assert( type(L1_neo).__name__ == 'ndarray' )
assert( L1_neo.shape == (3,3) )
assert( np.all(L1_neo == [[ 16.,  2.,  2.],[ 10.,  10.,  0.],[ 0.,  0.,  22.]]) )
L2_neo = confusion(testy, testy_L2)  
assert( np.all(L2_neo == [[ 17.,  1.,  2.],[ 10.,  10.,  0.],[ 0.,  0.,  22.]]) )

# 5. Some insights 


* In the test set, which class (NO, DH, or SL) was **most frequently** misclassified by the L1-based nearest neighbor classifier?
 - DH
* In the test set, which class (NO, DH, or SL) was **never** misclassified by the L2-based nearest neighbor classifier?
 - SL
* On **how many** of the test points did the two classification schemes (based on L1 and L2 distance) yield *different* predictions?
 - 7
